// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNsZBub6QDbFlxQRybreJyY7IJgMKGXsU',
    appId: '1:622858656476:web:4b1aafbafb15b656bbf219',
    messagingSenderId: '622858656476',
    projectId: 'gchat-reown',
    authDomain: 'gchat-reown.firebaseapp.com',
    storageBucket: 'gchat-reown.appspot.com',
    measurementId: 'G-X9C316G7GG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxhQPm2cREEXKQ6FV5U1D8S0bYIDjhbco',
    appId: '1:622858656476:android:9105e6c6dd89a432bbf219',
    messagingSenderId: '622858656476',
    projectId: 'gchat-reown',
    storageBucket: 'gchat-reown.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWVTx7dZHtMAYxHHXnBfD4ZrbediYx2pk',
    appId: '1:622858656476:ios:da7eab13a19f157dbbf219',
    messagingSenderId: '622858656476',
    projectId: 'gchat-reown',
    storageBucket: 'gchat-reown.appspot.com',
    iosBundleId: 'com.gchat.gchat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAWVTx7dZHtMAYxHHXnBfD4ZrbediYx2pk',
    appId: '1:622858656476:ios:da7eab13a19f157dbbf219',
    messagingSenderId: '622858656476',
    projectId: 'gchat-reown',
    storageBucket: 'gchat-reown.appspot.com',
    iosBundleId: 'com.gchat.gchat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBNsZBub6QDbFlxQRybreJyY7IJgMKGXsU',
    appId: '1:622858656476:web:6b14372c98b22a9fbbf219',
    messagingSenderId: '622858656476',
    projectId: 'gchat-reown',
    authDomain: 'gchat-reown.firebaseapp.com',
    storageBucket: 'gchat-reown.appspot.com',
    measurementId: 'G-VN0P0RNTB7',
  );
}
